"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LibraryCard = void 0;
const jsx_runtime_1 = require("react/jsx-runtime");
const react_router_dom_1 = require("react-router-dom");
const LibraryCard = ({ opt, sidebarCheck }) => {
    const history = react_router_dom_1.useHistory();
    return (jsx_runtime_1.jsxs("div", Object.assign({ onClick: () => {
            history.push(`/plugins_${opt.name}`);
            sidebarCheck();
        }, className: 'flex flex-col h-full max-w-lg mx-auto bg-gray-800 rounded-lg cursor-pointer' }, { children: [jsx_runtime_1.jsx("img", { className: 'rounded-lg rounded-b-none', src: 'http://www.3forty.media/ruki/wp-content/uploads/2020/06/meditation-yoga-1024x682.jpg', alt: 'thumbnail', loading: 'lazy' }, void 0), jsx_runtime_1.jsxs("div", Object.assign({ className: 'flex justify-between -mt-4 px-4' }, { children: [jsx_runtime_1.jsx("span", Object.assign({ className: 'inline-block ring-4 bg-primary ring-gray-800 rounded-full text-sm font-medium tracking-wide text-gray-100 px-3 pt-0.5' }, { children: opt.name }), void 0), jsx_runtime_1.jsx("span", Object.assign({ className: 'flex h-min space-x-1 items-center rounded-full text-gray-400 bg-gray-800 py-1 px-2 text-xs font-medium' }, { children: jsx_runtime_1.jsx("p", Object.assign({ className: 'text-blue-500 font-semibold text-xs' }, { children: opt.version }), void 0) }), void 0)] }), void 0), jsx_runtime_1.jsx("div", Object.assign({ className: 'py-2 px-4' }, { children: jsx_runtime_1.jsx("h1", Object.assign({ className: 'text-xl font-medium leading-6 tracking-wide text-gray-300 hover:text-blue-500 cursor-pointer' }, { children: jsx_runtime_1.jsx("a", { href: 'blog/detail' }, void 0) }), void 0) }), void 0), jsx_runtime_1.jsx("div", Object.assign({ className: 'px-4 space-y-2' }, { children: jsx_runtime_1.jsx("p", Object.assign({ className: 'text-gray-400 font-normal leading-5 tracking-wide' }, { children: opt.description }), void 0) }), void 0), jsx_runtime_1.jsx("div", Object.assign({ className: 'flex flex-row items-end h-full w-full px-4 mt-4' }, { children: jsx_runtime_1.jsxs("div", Object.assign({ className: 'flex border-t border-gray-700 w-full py-4' }, { children: [jsx_runtime_1.jsxs("div", Object.assign({ className: 'flex items-center space-x-3 border-r border-gray-700 w-full' }, { children: [jsx_runtime_1.jsx("img", { src: `https://robohash.org/${opt.author}?set=set4&size=35x35` }, void 0), jsx_runtime_1.jsx("div", { children: jsx_runtime_1.jsx("p", Object.assign({ className: 'text-sm font-semibold tracking-wide text-gray-200' }, { children: opt.author }), void 0) }, void 0)] }), void 0), jsx_runtime_1.jsx("div", Object.assign({ className: 'flex items-center flex-shrink-0 px-2' }, { children: jsx_runtime_1.jsxs("div", Object.assign({ className: 'flex items-center space-x-1 text-gray-400' }, { children: [jsx_runtime_1.jsx("svg", Object.assign({ xmlns: 'http://www.w3.org/2000/svg', className: 'h-5 w-5', fill: 'none', viewBox: '0 0 24 24', stroke: 'currentColor' }, { children: jsx_runtime_1.jsx("path", { strokeLinecap: 'round', strokeLinejoin: 'round', strokeWidth: 2, d: 'M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z' }, void 0) }), void 0), jsx_runtime_1.jsx("p", Object.assign({ className: 'font-medium' }, { children: "10" }), void 0)] }), void 0) }), void 0)] }), void 0) }), void 0)] }), void 0));
};
exports.LibraryCard = LibraryCard;
exports.default = exports.LibraryCard;
