"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const jsx_runtime_1 = require("react/jsx-runtime");
/* This example requires Tailwind CSS v2.0+ */
const react_1 = require("react");
const react_2 = require("@headlessui/react");
const Side = ({ children, open, setOpen }) => {
    return (jsx_runtime_1.jsx(react_2.Transition.Root, Object.assign({ show: open, as: react_1.Fragment }, { children: jsx_runtime_1.jsx(react_2.Dialog, Object.assign({ as: 'div', static: true, className: 'fixed inset-0 overflow-hidden', open: open, onClose: setOpen }, { children: jsx_runtime_1.jsxs("div", Object.assign({ className: 'absolute inset-0 overflow-hidden' }, { children: [jsx_runtime_1.jsx(react_2.Transition.Child, Object.assign({ as: react_1.Fragment, enter: 'ease-in-out duration-500', enterFrom: 'opacity-0', enterTo: 'opacity-100', leave: 'ease-in-out duration-500', leaveFrom: 'opacity-100', leaveTo: 'opacity-0' }, { children: jsx_runtime_1.jsx(react_2.Dialog.Overlay, { className: 'absolute inset-0 bg-gray-500 bg-opacity-75 transition-opacity' }, void 0) }), void 0), jsx_runtime_1.jsx("div", Object.assign({ className: 'fixed inset-y-0 right-0 pl-10 max-w-full flex' }, { children: jsx_runtime_1.jsx(react_2.Transition.Child, Object.assign({ as: react_1.Fragment, enter: 'transform transition ease-in-out duration-500 sm:duration-700', enterFrom: 'translate-x-full', enterTo: 'translate-x-0', leave: 'transform transition ease-in-out duration-500 sm:duration-700', leaveFrom: 'translate-x-0', leaveTo: 'translate-x-full' }, { children: jsx_runtime_1.jsxs("div", Object.assign({ className: 'relative w-screen max-w-md' }, { children: [jsx_runtime_1.jsx(react_2.Transition.Child, Object.assign({ as: react_1.Fragment, enter: 'ease-in-out duration-500', enterFrom: 'opacity-0', enterTo: 'opacity-100', leave: 'ease-in-out duration-500', leaveFrom: 'opacity-100', leaveTo: 'opacity-0' }, { children: jsx_runtime_1.jsx("div", Object.assign({ className: 'absolute top-0 left-0 -ml-8 pt-4 pr-2 flex sm:-ml-10 sm:pr-4' }, { children: jsx_runtime_1.jsxs("button", Object.assign({ className: 'rounded-md text-gray-300 hover:text-white focus:outline-none focus:ring-2 focus:ring-white', onClick: () => setOpen(false) }, { children: [jsx_runtime_1.jsx("span", Object.assign({ className: 'sr-only' }, { children: "Close panel" }), void 0), "X"] }), void 0) }), void 0) }), void 0), jsx_runtime_1.jsxs("div", Object.assign({ className: 'h-full flex flex-col py-6 bg-gray-300 dark:bg-gray-500 shadow-xl overflow-y-scroll' }, { children: [jsx_runtime_1.jsx("div", Object.assign({ className: 'px-4 sm:px-6' }, { children: jsx_runtime_1.jsx(react_2.Dialog.Title, Object.assign({ className: 'text-lg font-medium text-gray-900' }, { children: "Panel title" }), void 0) }), void 0), jsx_runtime_1.jsx("div", Object.assign({ className: 'mt-6 relative flex-1 px-4 sm:px-6' }, { children: children }), void 0)] }), void 0)] }), void 0) }), void 0) }), void 0)] }), void 0) }), void 0) }), void 0));
};
exports.default = Side;
